### ISSUE TITLE
Hamburger menu in left corner disappears when window width < 769px

### ISSUE THREAD

**Issue by kaganjd** [samatt/herbivore#23]
**Expected behavior**
- hamburger is always visible

**Comment by 0xStarcat** [comment]
Did this maybe get fixed? Looks visible for me here in the screenshot.

<img width="1313" alt="screen shot 2017-07-02 at 1 39 56 pm" src="https://user-images.githubusercontent.com/17187192/27772246-2852d2ac-5f2c-11e7-9f25-457f87115b1b.png">

**Comment by 0xStarcat** [comment]
Ditto ^^^ I was using an older version. NEVERMIND!

**Comment by kaganjd** [comment]
No more hamburger menu
