### ISSUE TITLE
NODE_MODULE_VERSION error

### ISSUE THREAD

**Issue by samatt** [samatt/herbivore#30]
for this problem
`was compiled against a different Node.js version using NODE_MODULE_VERSION 51. This version of Node.js requires NODE_MODULE_VERSION 53. `
possible solution
https://github.com/nodegit/nodegit/issues/1259#issuecomment-289600717

**Comment by samatt** [comment]
@kaganjd you were totally right about npmrc not working and I believe the reason it kept failing is becausee the arp-a npm module was being built from a binary that had a dependency to an old version of node. So what I've done now is for the arp-a repository and link that in the package json file. Can you do a clean install and see it runs without the need for a rebuild?

**Comment by kaganjd** [comment]
@samatt works for me! We should remove the `npm run rebuild` step from the readme too. I think you can add it to your last commit with `git commit --amend --no-edit`

**Comment by samatt** [comment]
didnt know that, thanks for the tip!
